
version: '3.8'

services:
  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - "4040:4040"
    environment:
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_SESSION_SECRET=${GITHUB_SESSION_SECRET}


  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - pyroscope

