
version: '3.9'

services:
  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - "4040:4040"
    environment:
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_SESSION_SECRET=${GITHUB_SESSION_SECRET}

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - pyroscope

  loadgen:
    image: curlimages/curl:latest
    depends_on:
      - app
    command: >
      sh -c 'while true; do
        for i in $(seq 1 100); do
          curl -v http://app:8080;
        done;
        echo "Batch of 100 requests done";
        sleep 1;
      done'

